import './globals.css'
import '../styles/custom.scss'

export const metadata = {
  title: 'Tani Permana',
    description: "Best online shop",
  description: 'Generated by create next app',
  icons: {
  icon: "/images/logo_tani.svg",
  },
}

export default function RootLayout({ children }) {
  return (
    <div className="mx-auto bg-white shadow-sm" style={{ maxWidth: '576px', minHeight: '100vh' }}> 

    <html lang="en">
    
        <body>{children}</body>
    </html>
    </div>
  )
}
