import './globals.css'
import '../styles/custom.scss'
import { Toaster } from '@/components/ui/sonner'


export const metadata = {
  title: 'Tani Permana',
  description: 'Best online shop',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/logo_tani.svg',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          className="mx-auto bg-white shadow-sm"
          style={{ maxWidth: '576px', height: '100vh' }}
        >
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  )
}
