# File: .github/workflows/main_sedulur-tani.yml

name: Build and deploy Node.js app to Azure Web App - sedulur-tani

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App (source-based)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sedulur-tani'
          slot-name: 'Production'
          package: .  # Kirim semua source code ke Azure
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AE83F1274AE648AAB6CCFC4492DAF372 }}
