name: Build and deploy Node.js app to Azure Web App - taniapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npx prisma generate
          npm run build --if-present
          npm run test --if-present

      - name: Copy static files (public & .next/static)
        run: |
          mkdir -p .next/standalone/public
          mkdir -p .next/standalone/.next/static
          cp -R ./public .next/standalone/public
          cp -R .next/static .next/standalone/.next/static

      - name: Copy Prisma client and schema
        run: |
          mkdir -p .next/standalone/node_modules/.prisma
          mkdir -p .next/standalone/node_modules/@prisma
          cp -R node_modules/.prisma .next/standalone/node_modules/
          cp -R node_modules/@prisma .next/standalone/node_modules/
          cp -R prisma .next/standalone/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .next/standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7F3D7991D47E403BA5B11B5378E15306 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4EEED0A1A2BC4A6EBED14E4B06396A8E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_256CD2C8D13141EFA1CD1A70F6312B36 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'taniapp'
          slot-name: 'Production'
          package: .
